---
title: "HW 1"
author: "Razmin Bari"
date: "09/05/2023"
output: 
  html_document:
    number_sections: true
---

We have now seen three ethical theories as well as their pitfalls.  We have also thoroughly discussed their applications to the justifiability of chatGPT.

# 

Now it is your turn to demonstrate your own understanding and mastery of these philosophical concepts.  To what extent, or under what circumstances, is the use of Chat-GPT justifiable in academic settings?  Use (at least) one of the above principles as a supporting argument for your position.  Argue for your position in one page or less.  (*Note: to use a principle discussed in class, you should first define it and then show how it is applicable in this case.  That is, utilitarians states... In the case of GPT it would argue that...*)

**Ans:** I am against the use of ChatGPT in academic settings.

The nature of GPT LLM is such that it uses data from all across the internet. While OpenAI claims that they do not seek information behind paywalls^1^, they are currently embroiled in multiple lawsuits with news agencies over copyright infringement.^2^ Besides, many scientific articles and books are available on the internet free of charge for the average person to read. However, if an essay is written with ChatGPT for a class assignment, for example, ChatGPT will not be able to provide proper citations for the sources it relied on - at least, at the present time, when ChatGPT is notorious for "hallucinating" citations. A piece of academic writing without citations is clear plagiarism, both on ChatGPT's part and also the student's (since they are the ones submitting it and hence indirectly claiming it as their original work). 

Deontology posits that an act is permissible if it, at all times, treats moral agents as ends, never merely as means to an end.^3^ Given the above background, deontologists would argue that the inherent copyright infringement & plagiarism as a whole by ChatGPT (and the student using it) does not treat 'moral agents' - or in this case, the authors of the original pieces of writing - as ends, only as means to one since the authors are not receiving the due monetary compensation or due credit. Additionally, the other formulation of deontology states that an act is permissible if you can universalize it without logical contradiction.^3^ As the inherent plagiarism here cannot be universalized since it is a form of deceiving, use of ChatGPT in academic writing cannot be justified.
    

# 

In no more than half a page, consider and refute a potential objection to the position you staked out in the above question. 

**Ans:** A way ChatGPT use *may* be morally justified is if a student uses it for brainstorming sessions. Since ChatGPT does not generate any 'new' ideas, as long as the student cites the original author who came up with the idea or concept, plagiarism does not occur.

I will attempt to refute this: Imagine you are brainstorming with somebody in real life. Their brain is being intellectually stimulated and the social interactions may bring forth positive feelings of fun or gratitude. The brainstorming might help them in their own work. Hence, the person is not used simply as a means. When you are using a search engine instead to learn about a topic to trigger your own brainstorming, you are generating traffic for the websites you are visiting. This traffic can be argued as giving due credit to the webpage authors. I reckon deontologists will argue here that brainstorming using ChatGPT uses the owner of the ideas ChatGPT is pulling as a means to an end since it is currently not possible to trace back where ChatGPT is getting that information unlike with a search engine, and ChatGPT's web scraping does not generate any traffic to the webpages it references. In conclusion, brainstorming using ChatGPT cannot be justified.

#

Submit a prompt to ChatGPT asking it to adopt the persona of a moral philosophy professor and defend whether the use of Chat GPT in academic settings is morally justifiable.  Specifically, you should prompt GPT to use the principle(s) you referenced in question 1.  Include a summary of the GPT response, and discuss how this differs or coincides with your response in question 1.  (In essence, we are curious whether GPT can justify itself!)  

**Ans:** My initial prompt to ChatGPT outputted that ChatGPT can be used if measures are taken to preserve the student's intellectual autonomy and if it is used only as "an auxiliary tool that enhances learning".^4^ This response went a different route and did not address any of the aforementioned concerns. 

I modified my prompt to make ChatGPT address the problems about plagiarism. The response changed significantly and coincided with my own response in that it could no longer as strongly justify its use. Since intellectual property cannot be properly respected, ChatGPT admits that its use may lead to deontological concerns regarding plagiarism. It does however still posit that ChatGPT can still be a useful educational tool and that perhaps its use can be continued if these limitations are "carefully managed".^4^ 



    
**References**

1. OpenAI. How ChatGPT and Our Language Models Are Developed | OpenAI Help Center. help.openai.com. Published 2023. https://help.openai.com/en/articles/7842364-how-chatgpt-and-our-language-models-are-developed

2. Niemeyer K, Varanasi L. OpenAI faces more lawsuits over copyrighted data used to train ChatGPT. Business Insider. Published June 30, 2024. https://www.businessinsider.com/openai-lawsuit-copyrighted-data-train-chatgpt-court-tech-ai-news-2024-6

3. Ackerman AT. Lecture on Deontology. Presented at: STOR 390; August 27, 2024.

4. ChatGPT. Response to query about the moral justifiability of using ChatGPT in academic settings. OpenAI. Accessed September 5, 2024.



